name: Build and Deploy Sphinx-based Documentation

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx sphinx-book-theme sphinx-copybutton

    - name: Build HTML
      run: |
        cd docs
        make html

    - name: List contents of build directory
      run: |
        ls -R docs/_build/html/

    - name: Copy .nojekyll
      run: |
        touch docs/_build/html/.nojekyll

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: html-docs
        path: docs/_build/html/

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.SPHINX_CICD_TOKEN }}
        publish_dir: docs/_build/html